package generator

import (
	"bufio"
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"strings"

	"github.com/ink-yht-code/sprout/sprout-gen/parser"
)

// Generator 负责根据解析后的 .sprout 文件生成代码。
type Generator struct {
	ModuleName  string // 模块名，用于 import
	ServicePath string // 服务目录路径
	File        *parser.SproutFile
}

// New 创建一个 Generator。
func New(moduleName, servicePath string, file *parser.SproutFile) *Generator {
	return &Generator{
		ModuleName:  moduleName,
		ServicePath: servicePath,
		File:        file,
	}
}

// Generate 生成所有代码。
//
// 会生成 types_gen.go，以及 handler_gen.go（若没有已有 handler.go）和 handlers.go（增量追加）。
func (g *Generator) Generate() error {
	if err := g.generateTypes(); err != nil {
		return fmt.Errorf("生成 types 失败: %w", err)
	}

	// 检测是否已有 handler.go（由 generate 命令生成）
	handlerPath := filepath.Join(g.ServicePath, "internal", "web", "handler.go")
	hasExistingHandler := false
	if _, err := os.Stat(handlerPath); err == nil {
		hasExistingHandler = true
	}

	// 只有在没有 handler.go 时才生成 handler_gen.go
	if !hasExistingHandler {
		if err := g.generateHandlerGen(); err != nil {
			return fmt.Errorf("生成 handler_gen 失败: %w", err)
		}
	}

	if err := g.generateHandlers(); err != nil {
		return fmt.Errorf("生成 handlers 失败: %w", err)
	}

	return nil
}

// generateTypes 生成 internal/types/types_gen.go
func (g *Generator) generateTypes() error {
	var buf strings.Builder
	buf.WriteString("// Code generated by sprout-gen. DO NOT EDIT.\n")
	buf.WriteString("// source: .sprout\n\n")
	buf.WriteString("package types\n\n")

	for _, t := range g.File.Types {
		buf.WriteString(fmt.Sprintf("// %s %s\n", t.Name, t.Name))
		buf.WriteString(fmt.Sprintf("type %s struct {\n", t.Name))
		for _, f := range t.Fields {
			goType := parser.GoType(f.Type)
			tag := f.Tags
			if tag != "" {
				// 自动添加 form tag 如果只有 json tag
				if strings.Contains(tag, `json:`) && !strings.Contains(tag, `form:`) {
					jsonRe := regexp.MustCompile(`json:"([^"]+)"`)
					jsonMatches := jsonRe.FindStringSubmatch(tag)
					if len(jsonMatches) > 1 {
						tag = tag + ` form:"` + jsonMatches[1] + `"`
					}
				}
				buf.WriteString(fmt.Sprintf("\t%s %s `%s`\n", f.Name, goType, tag))
			} else {
				buf.WriteString(fmt.Sprintf("\t%s %s\n", f.Name, goType))
			}
		}
		buf.WriteString("}\n\n")
	}

	typesPath := filepath.Join(g.ServicePath, "internal", "types", "types_gen.go")
	if err := os.MkdirAll(filepath.Dir(typesPath), 0755); err != nil {
		return err
	}
	return os.WriteFile(typesPath, []byte(buf.String()), 0644)
}

// generateHandlerGen 生成 internal/web/handler_gen.go
func (g *Generator) generateHandlerGen() error {
	var buf strings.Builder
	buf.WriteString("// Code generated by sprout-gen. DO NOT EDIT.\n")
	buf.WriteString("// source: .sprout\n\n")
	buf.WriteString("package web\n\n")
	buf.WriteString("import (\n")
	buf.WriteString("\t\"github.com/gin-gonic/gin\"\n")
	buf.WriteString("\t\"github.com/ink-yht-code/sprout\"\n")
	buf.WriteString(fmt.Sprintf("\t\"%s/internal/service\"\n", g.ModuleName))
	buf.WriteString(")\n\n")

	// Handler struct
	buf.WriteString("// Handler HTTP 处理器\n")
	buf.WriteString("type Handler struct {\n")
	buf.WriteString("\tsvc *service.Service\n")
	buf.WriteString("}\n\n")

	// NewHandler
	buf.WriteString("// NewHandler 创建 Handler\n")
	buf.WriteString("func NewHandler(svc *service.Service) *Handler {\n")
	buf.WriteString("\treturn &Handler{svc: svc}\n")
	buf.WriteString("}\n\n")

	// PrivateRoutes
	buf.WriteString("// PrivateRoutes 注册需要认证的路由\n")
	buf.WriteString("func (h *Handler) PrivateRoutes(server *gin.Engine) {\n")
	buf.WriteString("\t// TODO: 你可以在这里挂载鉴权中间件\n")
	for _, svc := range g.File.Services {
		prefix := g.File.Server.Prefix
		for _, endpoint := range svc.Private {
			fullPath := strings.TrimRight(prefix, "/") + endpoint.Path
			if prefix == "" {
				fullPath = endpoint.Path
			}
			if endpoint.Request != "" {
				buf.WriteString(fmt.Sprintf("\tserver.%s(\"%s\", sprout.B(h.%s))\n",
					endpoint.Method, fullPath, endpoint.Handler))
			} else {
				buf.WriteString(fmt.Sprintf("\tserver.%s(\"%s\", sprout.W(h.%s))\n",
					endpoint.Method, fullPath, endpoint.Handler))
			}
		}
	}
	buf.WriteString("}\n\n")

	// PublicRoutes
	buf.WriteString("// PublicRoutes 注册公开的路由\n")
	buf.WriteString("func (h *Handler) PublicRoutes(server *gin.Engine) {\n")
	for _, svc := range g.File.Services {
		prefix := g.File.Server.Prefix
		for _, endpoint := range svc.Public {
			fullPath := strings.TrimRight(prefix, "/") + endpoint.Path
			if prefix == "" {
				fullPath = endpoint.Path
			}
			if endpoint.Request != "" {
				buf.WriteString(fmt.Sprintf("\tserver.%s(\"%s\", sprout.B(h.%s))\n",
					endpoint.Method, fullPath, endpoint.Handler))
			} else {
				buf.WriteString(fmt.Sprintf("\tserver.%s(\"%s\", sprout.W(h.%s))\n",
					endpoint.Method, fullPath, endpoint.Handler))
			}
		}
	}
	buf.WriteString("}\n\n")

	// Health
	buf.WriteString("// Health 健康检查\n")
	buf.WriteString("func (h *Handler) Health(c *gin.Context) {\n")
	buf.WriteString("\tc.JSON(200, gin.H{\n")
	buf.WriteString("\t\t\"name\":        \"sprout\",\n")
	buf.WriteString("\t\t\"description\": \"基于 Gin 构建的 Go 微服务框架\",\n")
	buf.WriteString("\t\t\"version\":     \"1.0.0\",\n")
	buf.WriteString("\t})\n")
	buf.WriteString("}\n")

	handlerPath := filepath.Join(g.ServicePath, "internal", "web", "handler_gen.go")
	if err := os.MkdirAll(filepath.Dir(handlerPath), 0755); err != nil {
		return err
	}
	return os.WriteFile(handlerPath, []byte(buf.String()), 0644)
}

// generateHandlers 生成 internal/web/handlers.go（增量追加）
func (g *Generator) generateHandlers() error {
	handlerPath := filepath.Join(g.ServicePath, "internal", "web", "handlers.go")

	// 读取现有方法（增量追加）
	existing := make(map[string]struct{})
	if b, err := os.ReadFile(handlerPath); err == nil {
		existing = extractHandlerMethods(string(b))
	}

	var buf strings.Builder
	if _, err := os.Stat(handlerPath); os.IsNotExist(err) {
		// 创建新文件
		buf.WriteString("package web\n\n")
		buf.WriteString("import (\n")
		buf.WriteString("\t\"github.com/ink-yht-code/sprout\"\n")
		buf.WriteString(fmt.Sprintf("\t\"%s/internal/types\"\n", g.ModuleName))
		buf.WriteString(")\n\n")
	} else {
		// 文件存在：追加缺失的方法
		buf.WriteString("\n")
	}

	for _, svc := range g.File.Services {
		for _, endpoint := range append(svc.Public, svc.Private...) {
			if _, ok := existing[endpoint.Handler]; ok {
				continue
			}
			genHandlerMethodStub(&buf, endpoint)
		}
	}

	if buf.Len() == 0 || (buf.Len() == 1 && buf.String() == "\n") {
		return nil // 无新方法
	}

	if _, err := os.Stat(handlerPath); os.IsNotExist(err) {
		return os.WriteFile(handlerPath, []byte(buf.String()), 0644)
	}

	// 追加到现有文件
	f, err := os.OpenFile(handlerPath, os.O_APPEND|os.O_WRONLY, 0644)
	if err != nil {
		return err
	}
	defer f.Close()
	_, err = f.WriteString(buf.String())
	return err
}

func extractHandlerMethods(src string) map[string]struct{} {
	res := make(map[string]struct{})
	// func (h *Handler) MethodName(
	re := regexp.MustCompile(`func\s*\(h\s*\*Handler\)\s*([A-Za-z_][A-Za-z0-9_]*)\s*\(`)
	matches := re.FindAllStringSubmatch(src, -1)
	for _, m := range matches {
		if len(m) > 1 {
			res[m[1]] = struct{}{}
		}
	}
	return res
}

func genHandlerMethodStub(buf *strings.Builder, endpoint parser.APIEndpoint) {
	buf.WriteString(fmt.Sprintf("func (h *Handler) %s(", endpoint.Handler))
	if endpoint.Request != "" {
		buf.WriteString(fmt.Sprintf("ctx *sprout.Context, req types.%s", endpoint.Request))
	} else {
		buf.WriteString("ctx *sprout.Context")
	}
	buf.WriteString(") (sprout.Result, error) {\n")
	buf.WriteString("\t// TODO: 实现处理逻辑\n")
	buf.WriteString("\treturn sprout.Success(\"success\", nil), nil\n")
	buf.WriteString("}\n\n")
}

// GenerateService 从 .sprout 文件生成代码。
//
// moduleName 为空时会尝试从 go.mod 推断模块名。
func GenerateService(moduleName string, file *parser.SproutFile) error {
	// 获取当前目录名作为 servicePath
	cwd, err := os.Getwd()
	if err != nil {
		return err
	}
	servicePath := cwd

	// 如果不在服务目录内，尝试从 go.mod 获取模块名
	if moduleName == "" {
		moduleName = getModuleNameFromGoMod(servicePath)
	}

	gen := New(moduleName, servicePath, file)
	return gen.Generate()
}

// getModuleNameFromGoMod 从 go.mod 获取模块名
func getModuleNameFromGoMod(dir string) string {
	goModPath := filepath.Join(dir, "go.mod")
	data, err := os.ReadFile(goModPath)
	if err != nil {
		return ""
	}
	scanner := bufio.NewScanner(strings.NewReader(string(data)))
	for scanner.Scan() {
		line := strings.TrimSpace(scanner.Text())
		if strings.HasPrefix(line, "module ") {
			return strings.TrimPrefix(line, "module ")
		}
	}
	return ""
}
