package cmd

import (
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"strings"

	"github.com/fatih/color"
	"github.com/spf13/cobra"
)

// NewRepoCommand 创建 repo 子命令。
//
// 从 SQL DDL 中解析表结构并生成 DAO/Repository 相关代码。
func NewRepoCommand() *cobra.Command {
	cmd := &cobra.Command{
		Use:   "repo <name>",
		Short: "从 SQL DDL 生成 repository 代码",
		Long: `从 SQL DDL 文件生成 repository 代码。

示例:
  sprout gen repo user --ddl schema.sql
  sprout gen repo user --ddl schema.sql --table users`,
		Args: cobra.ExactArgs(1),
		Run: func(cmd *cobra.Command, args []string) {
			name := args[0]
			ddlFile, _ := cmd.Flags().GetString("ddl")
			table, _ := cmd.Flags().GetString("table")

			if ddlFile == "" {
				color.Red("错误: --ddl 是必须的")
				os.Exit(1)
			}

			if err := genRepo(name, ddlFile, table); err != nil {
				color.Red("错误: %v", err)
				os.Exit(1)
			}
			color.Green("✓ Repository 代码已生成: %s", name)
		},
	}

	cmd.Flags().StringP("ddl", "d", "", "SQL DDL 文件路径")
	cmd.Flags().StringP("table", "t", "", "表名（默认使用 name+s）")
	return cmd
}

// TableInfo 表信息。
type TableInfo struct {
	Name    string
	Columns []ColumnInfo
}

// ColumnInfo 列信息。
type ColumnInfo struct {
	Name     string
	Type     string
	Nullable bool
}

func genRepo(name, ddlFile, table string) error {
	// 默认表名
	if table == "" {
		table = name + "s"
	}

	// 解析 DDL
	tableInfo, err := parseDDL(ddlFile, table)
	if err != nil {
		return err
	}

	// 确定服务目录
	serviceDir := name
	if _, err := os.Stat(filepath.Join("internal", "domain")); err == nil {
		serviceDir = "."
	}

	// 生成 DAO model
	if err := genDAOModel(name, tableInfo, serviceDir); err != nil {
		return err
	}

	// 生成 DAO 实现
	if err := genDAORepo(name, tableInfo, serviceDir); err != nil {
		return err
	}

	// 生成 repository 接口
	if err := genRepoInterface(name, tableInfo, serviceDir); err != nil {
		return err
	}

	return nil
}

func parseDDL(ddlFile, tableName string) (*TableInfo, error) {
	data, err := os.ReadFile(ddlFile)
	if err != nil {
		return nil, err
	}

	info := &TableInfo{Name: tableName, Columns: make([]ColumnInfo, 0)}
	lines := strings.Split(string(data), "\n")

	// 查找 CREATE TABLE 行
	inTable := false
	tableNameLower := strings.ToLower(tableName)
	for _, line := range lines {
		line = strings.TrimSpace(line)
		lineUpper := strings.ToUpper(line)
		lineLower := strings.ToLower(line)

		// 检测 CREATE TABLE 开始
		if strings.Contains(lineUpper, "CREATE TABLE") {
			// 检查是否是目标表：支持 `tablename` 或 tablename
			if strings.Contains(line, "`"+tableName+"`") ||
				strings.Contains(lineLower, " "+tableNameLower+" ") ||
				strings.Contains(lineLower, " "+tableNameLower+"(") ||
				strings.Contains(lineLower, tableNameLower+" (") {
				inTable = true
			}
			continue
		}

		if !inTable {
			continue
		}

		// 检测表定义结束
		if strings.HasPrefix(line, ")") || strings.HasPrefix(line, "ENGINE") {
			break
		}

		// 移除尾部逗号和反引号
		line = strings.TrimSuffix(line, ",")
		line = strings.ReplaceAll(line, "`", "")

		// 跳过非列定义
		if line == "" || strings.HasPrefix(line, "PRIMARY") || strings.HasPrefix(line, "KEY") ||
			strings.HasPrefix(line, "INDEX") || strings.HasPrefix(line, "UNIQUE") ||
			strings.HasPrefix(line, "CONSTRAINT") || strings.HasPrefix(line, "FOREIGN") {
			continue
		}

		// 解析列定义: name TYPE(size) modifiers
		colRe := regexp.MustCompile(`^(\w+)\s+(\w+)(?:\([^)]*\))?(.*)$`)
		colMatches := colRe.FindStringSubmatch(line)
		if len(colMatches) >= 3 {
			col := ColumnInfo{
				Name: colMatches[1],
				Type: colMatches[2],
			}
			// 检查 NOT NULL
			rest := ""
			if len(colMatches) > 3 {
				rest = strings.ToUpper(colMatches[3])
			}
			col.Nullable = !strings.Contains(rest, "NOT NULL")
			info.Columns = append(info.Columns, col)
		}
	}

	if len(info.Columns) == 0 {
		return nil, fmt.Errorf("表 %s 未找到任何列定义", tableName)
	}

	return info, nil
}

func genDAOModel(name string, table *TableInfo, serviceDir string) error {
	moduleName := getModuleNameFromGoMod(serviceDir)
	if moduleName == "" {
		moduleName = name
	}

	var buf strings.Builder
	buf.WriteString("// Code generated by sprout-gen. DO NOT EDIT.\n\n")
	buf.WriteString("package dao\n\n")
	buf.WriteString("import \"time\"\n\n")
	buf.WriteString(fmt.Sprintf("// %s %s 表模型\n", strings.Title(name), table.Name))
	buf.WriteString(fmt.Sprintf("type %s struct {\n", strings.Title(name)))
	for _, col := range table.Columns {
		goType := sqlTypeToGo(col.Type, col.Nullable)
		fieldName := toCamelCase(col.Name)
		buf.WriteString(fmt.Sprintf("\t%s %s `gorm:\"column:%s\"`\n", fieldName, goType, col.Name))
	}
	buf.WriteString("}\n\n")
	buf.WriteString("// TableName 表名\n")
	buf.WriteString(fmt.Sprintf("func (%s) TableName() string {\n", strings.Title(name)))
	buf.WriteString(fmt.Sprintf("\treturn \"%s\"\n", table.Name))
	buf.WriteString("}\n")

	daoPath := filepath.Join(serviceDir, "internal", "repository", "dao", "model.go")
	return generateFile(daoPath, buf.String())
}

func genDAORepo(name string, table *TableInfo, serviceDir string) error {
	var buf strings.Builder
	buf.WriteString("// Code generated by sprout-gen. DO NOT EDIT.\n\n")
	buf.WriteString("package dao\n\n")
	buf.WriteString("import (\n")
	buf.WriteString("\t\"context\"\n")
	buf.WriteString("\t\"gorm.io/gorm\"\n")
	buf.WriteString(")\n\n")
	buf.WriteString(fmt.Sprintf("// %sDAO %s 数据访问对象\n", strings.Title(name), name))
	buf.WriteString(fmt.Sprintf("type %sDAO struct {\n", strings.Title(name)))
	buf.WriteString("\tdb *gorm.DB\n")
	buf.WriteString("}\n\n")
	buf.WriteString(fmt.Sprintf("// New%sDAO 创建 DAO\n", strings.Title(name)))
	buf.WriteString(fmt.Sprintf("func New%sDAO(db *gorm.DB) *%sDAO {\n", strings.Title(name), strings.Title(name)))
	buf.WriteString(fmt.Sprintf("\treturn &%sDAO{db: db}\n", strings.Title(name)))
	buf.WriteString("}\n\n")
	buf.WriteString("// Create 创建记录\n")
	buf.WriteString(fmt.Sprintf("func (d *%sDAO) Create(ctx context.Context, m *%s) error {\n", strings.Title(name), strings.Title(name)))
	buf.WriteString("\treturn d.db.WithContext(ctx).Create(m).Error\n")
	buf.WriteString("}\n\n")
	buf.WriteString("// GetByID 根据 ID 获取\n")
	buf.WriteString(fmt.Sprintf("func (d *%sDAO) GetByID(ctx context.Context, id int64) (*%s, error) {\n", strings.Title(name), strings.Title(name)))
	buf.WriteString(fmt.Sprintf("\tvar m %s\n", strings.Title(name)))
	buf.WriteString("\terr := d.db.WithContext(ctx).Where(\"id = ?\", id).First(&m).Error\n")
	buf.WriteString("\treturn &m, err\n")
	buf.WriteString("}\n\n")
	buf.WriteString("// Update 更新记录\n")
	buf.WriteString(fmt.Sprintf("func (d *%sDAO) Update(ctx context.Context, m *%s) error {\n", strings.Title(name), strings.Title(name)))
	buf.WriteString("\treturn d.db.WithContext(ctx).Save(m).Error\n")
	buf.WriteString("}\n\n")
	buf.WriteString("// Delete 删除记录\n")
	buf.WriteString(fmt.Sprintf("func (d *%sDAO) Delete(ctx context.Context, id int64) error {\n", strings.Title(name)))
	buf.WriteString("\treturn d.db.WithContext(ctx).Delete(&" + strings.Title(name) + "{}, id).Error\n")
	buf.WriteString("}\n")

	repoPath := filepath.Join(serviceDir, "internal", "repository", "dao", "repo.go")
	return generateFile(repoPath, buf.String())
}

func genRepoInterface(name string, table *TableInfo, serviceDir string) error {
	var buf strings.Builder
	buf.WriteString("package port\n\n")
	buf.WriteString("import (\n")
	buf.WriteString("\t\"context\"\n")
	buf.WriteString(fmt.Sprintf("\t\"%s/internal/domain/entity\"\n", getModuleNameFromGoMod(serviceDir)))
	buf.WriteString(")\n\n")
	buf.WriteString(fmt.Sprintf("// %sRepository %s 仓库接口\n", strings.Title(name), name))
	buf.WriteString(fmt.Sprintf("type %sRepository interface {\n", strings.Title(name)))
	buf.WriteString(fmt.Sprintf("\tCreate(ctx context.Context, entity *entity.%s) error\n", strings.Title(name)))
	buf.WriteString(fmt.Sprintf("\tGetByID(ctx context.Context, id int64) (*entity.%s, error)\n", strings.Title(name)))
	buf.WriteString(fmt.Sprintf("\tUpdate(ctx context.Context, entity *entity.%s) error\n", strings.Title(name)))
	buf.WriteString("\tDelete(ctx context.Context, id int64) error\n")
	buf.WriteString("}\n")

	portPath := filepath.Join(serviceDir, "internal", "domain", "port", strings.ToLower(name)+"_repo.go")
	return generateFile(portPath, buf.String())
}

func sqlTypeToGo(sqlType string, nullable bool) string {
	sqlType = strings.ToUpper(sqlType)
	var goType string

	switch {
	case strings.Contains(sqlType, "INT"):
		if strings.Contains(sqlType, "BIGINT") {
			goType = "int64"
		} else if strings.Contains(sqlType, "SMALLINT") || strings.Contains(sqlType, "TINYINT") {
			goType = "int8"
		} else {
			goType = "int"
		}
	case strings.Contains(sqlType, "VARCHAR") || strings.Contains(sqlType, "TEXT") || strings.Contains(sqlType, "CHAR"):
		goType = "string"
	case strings.Contains(sqlType, "BOOL"):
		goType = "bool"
	case strings.Contains(sqlType, "FLOAT") || strings.Contains(sqlType, "DOUBLE"):
		goType = "float64"
	case strings.Contains(sqlType, "DECIMAL"):
		goType = "float64"
	case strings.Contains(sqlType, "DATE") || strings.Contains(sqlType, "TIME"):
		goType = "time.Time"
	case strings.Contains(sqlType, "JSON"):
		goType = "string"
	default:
		goType = "string"
	}

	if nullable {
		return "*" + goType
	}
	return goType
}

func toCamelCase(s string) string {
	parts := strings.Split(s, "_")
	for i, p := range parts {
		if len(p) > 0 {
			parts[i] = strings.ToUpper(p[:1]) + p[1:]
		}
	}
	return strings.Join(parts, "")
}
