package cmd

import (
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"

	"github.com/fatih/color"
	"github.com/spf13/cobra"
)

// NewRPCCommand 创建 rpc 子命令。
//
// 从 .proto 文件生成 gRPC 代码，并生成 server wrapper 骨架。
func NewRPCCommand() *cobra.Command {
	cmd := &cobra.Command{
		Use:   "rpc <name>",
		Short: "从 .proto 文件生成 gRPC 代码",
		Long: `从 .proto 文件生成 gRPC 代码。

需要安装:
  - protoc
  - protoc-gen-go
  - protoc-gen-go-grpc

示例:
  sprout gen rpc user                  # 解析 user/user.proto
  sprout gen rpc user --file my.proto  # 指定文件`,
		Args: cobra.ExactArgs(1),
		Run: func(cmd *cobra.Command, args []string) {
			name := args[0]
			file, _ := cmd.Flags().GetString("file")
			if file == "" {
				file = filepath.Join(name, name+".proto")
			}

			if err := genRPC(name, file); err != nil {
				color.Red("错误: %v", err)
				os.Exit(1)
			}
			color.Green("✓ RPC 代码已生成: %s", name)
		},
	}

	cmd.Flags().StringP("file", "f", "", ".proto 文件路径")
	return cmd
}

func genRPC(name, file string) error {
	// 检查 protoc 是否安装
	if _, err := exec.LookPath("protoc"); err != nil {
		return fmt.Errorf("protoc 未安装，请先安装 protoc")
	}

	// 获取绝对路径
	absFile, err := filepath.Abs(file)
	if err != nil {
		return err
	}

	protoDir := filepath.Dir(absFile)
	protoName := filepath.Base(absFile)

	// 生成 gRPC 代码
	// protoc --go_out=. --go_opt=paths=source_relative \
	//        --go-grpc_out=. --go-grpc_opt=paths=source_relative \
	//        user.proto
	args := []string{
		"--go_out=.",
		"--go_opt=paths=source_relative",
		"--go-grpc_out=.",
		"--go-grpc_opt=paths=source_relative",
		protoName,
	}

	fmt.Printf("Running: protoc %s\n", strings.Join(args, " "))

	execCmd := exec.Command("protoc", args...)
	execCmd.Dir = protoDir
	execCmd.Stdout = os.Stdout
	execCmd.Stderr = os.Stderr

	if err := execCmd.Run(); err != nil {
		return fmt.Errorf("protoc 执行失败: %w", err)
	}

	// 确定服务目录
	serviceDir := name
	if _, err := os.Stat(filepath.Join("internal", "domain")); err == nil {
		serviceDir = "."
	}

	// 生成 server wrapper
	if err := genRPCServer(name, serviceDir); err != nil {
		return err
	}

	return nil
}

func genRPCServer(name, serviceDir string) error {
	moduleName := getModuleNameFromGoMod(serviceDir)
	if moduleName == "" {
		moduleName = name
	}

	serverCode := fmt.Sprintf(`// Code generated by sprout-gen. DO NOT EDIT.

package web

import (
	"context"

	"google.golang.org/grpc"
	"%s/internal/service"
	pb "%s/api/proto"
)

// RPCServer gRPC 服务包装器
type RPCServer struct {
	Unimplemented%sServer
	svc *service.Service
}

// NewRPCServer 创建 RPC Server
func NewRPCServer(svc *service.Service) *RPCServer {
	return &RPCServer{svc: svc}
}

// Register 注册到 gRPC Server
func (s *RPCServer) Register(server grpc.ServiceRegistrar) {
	Register%sServer(server, s)
}
`, moduleName, moduleName, strings.Title(name), strings.Title(name))

	rpcPath := filepath.Join(serviceDir, "internal", "web", "rpc.go")
	return generateFile(rpcPath, serverCode)
}
