package scaffoldtmpl

// HTTPTmpl HTTP handler 模板
var HTTPTmpl = `// Code generated by gint-gen. DO NOT EDIT.
// source: {{.Name}}.gint

package web

import (
	"github.com/gin-gonic/gin"
	"{{.Name}}/internal/service"
)

// Handler HTTP 处理器
type Handler struct {
	svc service.{{.NameUpper}}Service
}

// NewHandler 创建 Handler
func NewHandler(svc service.{{.NameUpper}}Service) *Handler {
	return &Handler{svc: svc}
}

// RegisterRoutes 注册路由
func (h *Handler) RegisterRoutes(server *gin.Engine) {
	// 公开路由（不需要认证）
	h.PublicRoutes(server)
	
	// 私有路由（需要认证）
	// 使用 CheckLoginMiddleware 进行登录校验
	h.PrivateRoutes(server)
}

// PublicRoutes 注册公开的路由
func (h *Handler) PublicRoutes(server *gin.Engine) {
	// 示例路由
	// server.GET("/api/{{.Name}}/:id", h.GetByID)
	// server.POST("/api/{{.Name}}", h.Create)
}

// PrivateRoutes 注册需要认证的路由
func (h *Handler) PrivateRoutes(server *gin.Engine) {
	// 使用 CheckLoginMiddleware 进行登录校验
	// privateGroup := server.Group("/api/{{.Name}}")
	// privateGroup.Use(ginx.CheckLoginMiddleware())
	// {
	// 	privateGroup.PUT("/:id", h.Update)
	// 	privateGroup.DELETE("/:id", h.Delete)
	// }
	
	// TODO: 添加需要认证的路由
	// 可以在这里添加会员校验中间件
	// memberGroup := privateGroup.Use(checkMembershipMiddleware())
	// memberGroup.GET("/profile", h.GetProfile)
}

func (h *Handler) Health(c *gin.Context) {
	c.JSON(200, gin.H{
		"name":        "gint",
		"description": "基于 Gin 构建的 Go 微服务框架，提供路由、认证、校验等开箱即用的功能",
		"version":     "1.0.0",
	})
}
`
