package scaffoldtmpl

// TypesTmpl types 模板（VO - View Object）
var TypesTmpl = `// Code generated by gint-gen. DO NOT EDIT.
// source: {{.Name}}.gint

package web

// Create{{.NameUpper}}Req 创建{{.Name}}请求
type Create{{.NameUpper}}Req struct {
	Name string ` + "`" + `json:"name" binding:"required"` + "`" + `
	// TODO: 添加其他字段
}

// Update{{.NameUpper}}Req 更新{{.Name}}请求
type Update{{.NameUpper}}Req struct {
	ID   string ` + "`" + `json:"id" binding:"required"` + "`" + `
	Name string ` + "`" + `json:"name" binding:"required"` + "`" + `
	// TODO: 添加其他字段
}

// {{.NameUpper}}Resp {{.Name}}响应
type {{.NameUpper}}Resp struct {
	ID   string ` + "`" + `json:"id"` + "`" + `
	Name string ` + "`" + `json:"name"` + "`" + `
	// TODO: 添加其他字段
}
`
