package scaffoldtmpl

// MockRepositoryTmpl Mock Repository 模板
var MockRepositoryTmpl = `// Code generated by mockgen. DO NOT EDIT.
// Source: internal/repository/{{.Name}}_repository.go

package mocks

import (
	"context"
	reflect "reflect"

	"{{.Name}}/internal/domain"
	gomock "github.com/golang/mock/gomock"
)

// Mock{{.NameUpper}}Repository is a mock of {{.NameUpper}}Repository interface.
type Mock{{.NameUpper}}Repository struct {
	ctrl     *gomock.Controller
	recorder *Mock{{.NameUpper}}RepositoryMockRecorder
}

// Mock{{.NameUpper}}RepositoryMockRecorder is the mock recorder for Mock{{.NameUpper}}Repository.
type Mock{{.NameUpper}}RepositoryMockRecorder struct {
	mock *Mock{{.NameUpper}}Repository
}

// NewMock{{.NameUpper}}Repository creates a new mock instance.
func NewMock{{.NameUpper}}Repository(ctrl *gomock.Controller) *Mock{{.NameUpper}}Repository {
	mock := &Mock{{.NameUpper}}Repository{ctrl: ctrl}
	mock.recorder = &Mock{{.NameUpper}}RepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Mock{{.NameUpper}}Repository) EXPECT() *Mock{{.NameUpper}}RepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *Mock{{.NameUpper}}Repository) Create(ctx context.Context, u *domain.{{.NameUpper}}) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, u)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *Mock{{.NameUpper}}RepositoryMockRecorder) Create(ctx, u interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*Mock{{.NameUpper}}Repository)(nil).Create), ctx, u)
}

// FindByID mocks base method.
func (m *Mock{{.NameUpper}}Repository) FindByID(ctx context.Context, id string) (*domain.{{.NameUpper}}, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", ctx, id)
	ret0, _ := ret[0].(*domain.{{.NameUpper}})
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *Mock{{.NameUpper}}RepositoryMockRecorder) FindByID(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*Mock{{.NameUpper}}Repository)(nil).FindByID), ctx, id)
}

// Update mocks base method.
func (m *Mock{{.NameUpper}}Repository) Update(ctx context.Context, u *domain.{{.NameUpper}}) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, u)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *Mock{{.NameUpper}}RepositoryMockRecorder) Update(ctx, u interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*Mock{{.NameUpper}}Repository)(nil).Update), ctx, u)
}

// Delete mocks base method.
func (m *Mock{{.NameUpper}}Repository) Delete(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *Mock{{.NameUpper}}RepositoryMockRecorder) Delete(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*Mock{{.NameUpper}}Repository)(nil).Delete), ctx, id)
}
`
