package scaffoldtmpl

// MockServiceTmpl Mock Service 模板
var MockServiceTmpl = `// Code generated by mockgen. DO NOT EDIT.
// Source: internal/service/{{.Name}}.go

package mocks

import (
	"context"
	reflect "reflect"

	"{{.Name}}/internal/domain"
	gomock "github.com/golang/mock/gomock"
)

// Mock{{.NameUpper}}Service is a mock of {{.NameUpper}}Service interface.
type Mock{{.NameUpper}}Service struct {
	ctrl     *gomock.Controller
	recorder *Mock{{.NameUpper}}ServiceMockRecorder
}

// Mock{{.NameUpper}}ServiceMockRecorder is the mock recorder for Mock{{.NameUpper}}Service.
type Mock{{.NameUpper}}ServiceMockRecorder struct {
	mock *Mock{{.NameUpper}}Service
}

// NewMock{{.NameUpper}}Service creates a new mock instance.
func NewMock{{.NameUpper}}Service(ctrl *gomock.Controller) *Mock{{.NameUpper}}Service {
	mock := &Mock{{.NameUpper}}Service{ctrl: ctrl}
	mock.recorder = &Mock{{.NameUpper}}ServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Mock{{.NameUpper}}Service) EXPECT() *Mock{{.NameUpper}}ServiceMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *Mock{{.NameUpper}}Service) Create(ctx context.Context, u *domain.{{.NameUpper}}) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, u)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *Mock{{.NameUpper}}ServiceMockRecorder) Create(ctx, u interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*Mock{{.NameUpper}}Service)(nil).Create), ctx, u)
}

// FindByID mocks base method.
func (m *Mock{{.NameUpper}}Service) FindByID(ctx context.Context, id string) (*domain.{{.NameUpper}}, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", ctx, id)
	ret0, _ := ret[0].(*domain.{{.NameUpper}})
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *Mock{{.NameUpper}}ServiceMockRecorder) FindByID(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*Mock{{.NameUpper}}Service)(nil).FindByID), ctx, id)
}

// Update mocks base method.
func (m *Mock{{.NameUpper}}Service) Update(ctx context.Context, u *domain.{{.NameUpper}}) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, u)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *Mock{{.NameUpper}}ServiceMockRecorder) Update(ctx, u interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*Mock{{.NameUpper}}Service)(nil).Update), ctx, u)
}

// Delete mocks base method.
func (m *Mock{{.NameUpper}}Service) Delete(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *Mock{{.NameUpper}}ServiceMockRecorder) Delete(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*Mock{{.NameUpper}}Service)(nil).Delete), ctx, id)
}
`
