package scaffoldtmpl

// WireGenTmpl Wire 生成文件模板
var WireGenTmpl = `// Code generated by Wire. DO NOT EDIT.

//go:build !wireinject
// +build !wireinject

package {{.Name}}

import (
	"github.com/ink-yht-code/sprout/jwt"
	"github.com/redis/go-redis/v9"
	"gorm.io/gorm"

	"{{.Name}}/internal/repository"
	"{{.Name}}/internal/repository/cache"
	"{{.Name}}/internal/repository/dao"
	"{{.Name}}/internal/service"
	"{{.Name}}/internal/web"
)

// InitModule 初始化模块（由 Wire 生成）
func InitModule(db *gorm.DB, rdb redis.Cmdable, jwtManager jwt.Manager) *Module {
	{{.NameUpper}}DAO := dao.New{{.NameUpper}}DAO(db)
	{{.NameUpper}}Cache := cache.New{{.NameUpper}}Cache(rdb)
	{{.NameUpper}}Repository := repository.New{{.NameUpper}}Repository({{.NameUpper}}DAO, {{.NameUpper}}Cache)
	{{.NameUpper}}Service := service.New{{.NameUpper}}Service({{.NameUpper}}Repository, jwtManager)
	handler := web.NewHandler({{.NameUpper}}Service)
	module := &Module{
		Hdl: handler,
		Svc: {{.NameUpper}}Service,
	}
	return module
}

type Module struct {
	Hdl *web.Handler
	Svc service.{{.NameUpper}}Service
}
`
